### ISSUE TITLE
NuGet package request!

### ISSUE THREAD

**Issue by Seng-Jik** [Wbooru/EHentaiAPI#3]
I'm developing a anime wallpaper downloader [QwQ](https://github.com/Seng-Jik/QwQ), I want to add EHentai support to this library.
Please publish EHentaiAPI to NuGet.

**Comment by MikiraSora** [comment]
试一下吧:https://www.nuget.org/packages/EHentaiAPI
目前还算是绝大部分功能能用，但有些功能需要用户登录。
可能后面还有比较大的变动

**Comment by Seng-Jik** [comment]
Thanks!
